import { gql } from 'graphql-request';

const getAllCreditMemoGQL = gql`
  query creditMemos(
    $orderBy: [CreditMemoOrderBy]
    $filter: CreditMemoFilter
    $first: Int
    $after: String
    $last: Int
    $before: String
  ) {
    creditMemos(
      filter: $filter
      orderBy: $orderBy
      first: $first
      after: $after
      last: $last
      before: $before
    ) {
      totalCount
      pageInfo{
        startCursor
        endCursor
        hasPreviousPage
        hasNextPage
      }
      nodes
      {
        id
        amountAvailable
        amountUsed
        creditMemoAppliedDate
        creditMemoCreationDate
        creditMemoNumber
        currency
        initialStatus
        tenant
        status
        subTotal
        taxDetails{
          taxAmount
          taxType{
            id
            name
            rate
            strategy
          }
          taxableAmount
        }
        total
        totalTax
        seller{
          invoiceLogoUrl
          invoiceMemo
          invoiceText
          merchantOfRecord{
            ... on CreditMemoParty {
              user{
                current{
                  id
                }
              }
            }
            ... on CreditMemoMarketplace {
              name
            }
          }
        }
        customer{
          account{
            current{
              id
            }
            recorded{
              name
            }
          }
          user{
            current{
              id
            }
            recorded{
              email
              firstName
              lastName
              addresses{
                type
                address{
                  city
                  country
                  postalCode
                  region
                  streetLine1
                  streetLine2
                }
              }
            }
          }
        }
        creditMemoLines{
          id
          buyer{
            account{
              current{
                id
              }
              recorded{
                name
              }
            }
            user{
              current{
                id
              }
              recorded{
                email
                firstName
                lastName
                addresses{
                  type
                  address{
                    city
                    country
                    postalCode
                    region
                    streetLine1
                    streetLine2
                  }
                }
              }
            }
          }
          cost{
            credit
            percentage
            strategy
            type{
              recorded{
                description
                feeLabel
                type
              }
            }
            typeCategory
            unit{
              recorded{
                allowDecimals
                feeLabel
                unitLabel
                unitsLabel
              }
            }
          }
          costPeriod{
            recorded{
              feeLabel
              periodLabel
              periodsLabel
              unit
              unitValue
            }
          }
          description
          discount{
            recorded{
              code
              description
              type
              unit{
                maximum
                minimum
                unitName
              }
              value
            }
          }
          edition{
            current{
              id
              version
            }
            recorded{
              name
            }
          }
          orderLineId
          period{
            end
            start
          }
          pricingPlan{
            current{
              id
            }
            recorded{
              period
            }
          }
          product{
            current{
              id
              version
            }
            recorded{
              name
            }
          }
          provider{
            account{
              current{
                id
              }
              recorded{
                name
              }
            }
            user{
              current{
                id
              }
              recorded{
                email
                firstName
                lastName
                addresses{
                  type
                  address{
                    city
                    country
                    postalCode
                    region
                    streetLine1
                    streetLine2
                  }
                }
              }
            }
          }
          quantity
          subscription{
            current{
              id
            }
          }
          total
          type
          unitPrice
        }
      }
    }
  }
`;

export default getAllCreditMemoGQL;
