export const ROLES = {
  RESELLER_MANAGER: 'RESELLER_MANAGER',
  RESELLER: 'RESELLER',
  CHANNEL_ADMIN: 'CHANNEL_ADMIN',
  CHANNEL_SUPPORT: 'CHANNEL_SUPPORT',
  CHANNEL_PRODUCT_SUPPORT: 'CHANNEL_PRODUCT_SUPPORT',
  CORPORATE_ADMIN: 'CORPORATE_ADMIN',
  REPORTS_CHANNEL_ADMIN: 'REPORTS_CHANNEL_ADMIN',
  DEVELOPER: 'DEVELOPER',
  USER: 'USER'
};
