export const SET_FLAG = 'SET_FLAG';
export const SET_FLAG_STARTED = 'SET_FLAG_STARTED';
export const SET_FLAG_SUCCESS = 'SET_FLAG_SUCCESS';
export const SET_FLAG_FAILURE = 'SET_FLAG_FAILURE';

export const FETCHING_TRANSLATIONS = 'FETCHING_TRANSLATIONS';
export const FETCHING_TRANSLATIONS_FAILURE = 'FETCHING_TRANSLATIONS_FAILURE';
export const FETCHING_TRANSLATIONS_SUCCESS = 'FETCHING_TRANSLATIONS_SUCCESS';

export const FETCH_MEMO_LIST = 'FETCH_MEMO_LIST';
export const FETCH_MEMO_LIST_FAILURE = 'FETCH_MEMO_LIST_FAILURE';
export const FETCH_MEMO_LIST_SUCCESS = 'FETCH_MEMO_LIST_SUCCESS';

export const FETCH_MEMO_DETAILS_FAILURE = 'FETCH_MEMO_DETAILS_FAILURE';
export const FETCH_MEMO_DETAILS_SUCCESS = 'FETCH_MEMO_DETAILS_SUCCESS';
export const FETCHING_MEMO_DETAILS = 'FETCHING_MEMO_DETAILS';

export const SET_MEMO_DETAILS = 'SET_MEMO_DETAILS';

export const FETCH_UPDATED_CURRENT_PAGE = 'FETCH_UPDATED_CURRENT_PAGE';

export const FETCH_UPDATED_CURRENT_PAGE = 'FETCH_UPDATED_CURRENT_PAGE';
